import './globals.css'
import 'highlight.js/styles/atom-one-dark.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { getServerSession } from "next-auth";
import SessionProvider from '@/components/SessionProvider';
import { authOptions } from './api/auth/[...nextauth]/route';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Header/>
          <main>{children}</main>
          <Footer/>
        </SessionProvider>
      </body>
    </html>
  )
}
